# Generated by Django 5.2 on 2025-04-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBaseModel',
            fields=[
            ],
        ),
    ]
